---
# Below is the configuration information required for the application

name: ""
description: "A Telegram Utility and Group Management Bot which will provide a range of useful features to users."
logo: ""
keywords:
  - "python-telegram-bot"
  - "telegram"
  - "utility bot"
  - "group bot"
  - "python"
  - "sub mecha"
repository: "https://github.com/caidol/SUB_Mecha"

env: 
  BOT_TOKEN: 
    description: "The bot token that can be created and retrieved from @BotFather."
    value: ""
    required: true
  
  BOT_USERNAME:
    description: "The username that you have created for your bot."
    value: ""
    required: true

  BOT_NAME:
   description: "The name that you have created for your bot."
   value: ""
   required: true

  OWNER_ID:
    description: "The Telegram ID of the owner of the bot."
    value: ""
    required: true # might need to change this

  OWNER_USERNAME: 
    description: "Your Telegram username."
    value: ""
    required: true

  OWM_API_TOKEN:
    description: "The Open Weather Map API token in order to access weather data."
    value: ""
    required: true
...