---
# Below is the configuration information required for the application

name: "SUB_Mecha"
description: "A Telegram Utility and Group Management Bot which will provide a range of useful features to users."
logo: ""
keywords:
  - "python-telegram-bot"
  - "telegram"
  - "utility bot"
  - "group bot"
  - "python"
  - "sub mecha"
repository: "https://github.com/caidol/SUB_Mecha"

env: 
  BOT_TOKEN: 
    description: "The bot token that can be created and retrieved from @BotFather"
    value: "" # remove when committing
    required: true
  
  BOT_USERNAME:
    description: "The username that you have created for your bot"
    value: "sub_mecha_bot"
    required: true

  BOT_NAME:
   description: "The name that you have created for your bot."
   value: "SUB Mecha Bot"
   required: true

  OWNER_ID:
    description: "The telegram id of the owner of the bot"
    value: "5472502746"
    required: true # might need to change this

  OWNER_USERNAME: 
    description: "Your telegram username"
    value: "ai_dan12"
    required: true

  OWM_API_TOKEN:
    description: "The Open Weather Map API token in order to access weather data."
    value: "" # remove when committing
    required: true
...